services:
  db:
    image: pgvector/pgvector:pg17
    container_name: memory_base_db
    environment:
      POSTGRES_USER: memory
      POSTGRES_PASSWORD: memory
      POSTGRES_DB: memory_base
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
